### ISSUE TITLE
Slightly inaccurate information in the lesson

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/fewpjs-queryselector-methods#1]
After showing how to use the `querySelector()` method:

```
// get <li>2</li>
const li2 = document.querySelector('ul.ranked-list li ul li')
 
// get <div>4</div>
const div4 = document.querySelector('ul.unranked-list li div')
```

The lesson states:

> In the above example, the first query says, "Starting from `document` (the object we've called querySelector() on), find a `ul` with a `className` of `ranked-list` (the `.` is for `className`).
> 
> Then find an `li` that is a child of that `ul`. Then find a `ul` that is a child (but not necessarily a direct descendant) of that `li`. Finally, find an `li` that is a child of that (second) `ul`."

However, that information isn't quite true. What that first query is really doing is finding an `li` that is a descendant of the `ul` whose className is `ranked-list`, then finding a `ul` that is a descendant (but not necessarily a direct child) of that `li`, and finally finding an `li` that is a descendant of that (second) `ul`.

It's a small difference, but it's important to distinguish between a child and a descendant. Since this is an easy fix, I'll submit a pull request for it.

--- Sdcrouse

**Comment by lizbur10** [comment]
Hello,

Your pull request has been merged so I'm closing this issue. Thank you for contributing to a learn-co-curriculum repository! 💙
